(library
 (name cucumber)
 (public_name cucumber)
 (libraries cmdliner re re.perl str sedlex menhirLib unix)
 (flags
  (:standard -w -42))
 (preprocess
  (pps sedlex.ppx))
 (modules
  gherkin_ast
  gherkin_keywords
  gherkin_parser
  lex
  parser
  pickle
  step
  tag
  table
  location
  docstring
  dialect
  color
  lib
  report
  outcome
  cucumber))

(menhir
 (modules parser)
 (flags --table))
