(library
 (name cucumber)
 (public_name cucumber)
 (libraries cmdliner re re.perl str sedlex menhirLib unix)
 (flags
  (:standard -w -42-32))
 (preprocess
  (pps sedlex.ppx))
 (modules
  effects
  gherkin_ast
  gherkin_keywords
  gherkin_keywords_data
  gherkin_parser_intf
  gherkin_parser_pure
  lex
  parser
  pickle
  step
  step_registry
  tag
  table
  location
  docstring
  dialect
  color
  lib
  report
  outcome
  cucumber))

(menhir
 (modules parser))

(rule
 (target gherkin_keywords_data.ml)
 (deps
  (:gen ../bin/gen_keywords/gen.exe)
  (:json %{project_root}/vendor/gherkin-languages.json))
 (action
  (with-stdout-to %{target}
   (run %{gen} %{json}))))
